Drafttest
pitt-software-practices/ames_qsar pull request #4
Opened 2020-10-12 13:43 UTC by twsleight

adding .gitignore, the out_fileread.py script for reading gaussian .out files and the test for the out_fileread.py script.

2020-10-12 14:28 UTC, paulboone requested changes

2020-10-12 14:28 UTC, paulboone commented on ames_qsar/out_fileread.py
> +    import glob
imports should be at top of file

2020-10-12 14:28 UTC, paulboone commented on ames_qsar/out_fileread.py
> +    #    print(filename)
debugging prints / comments should not be part of final PR

2020-10-12 14:28 UTC, paulboone commented on tests/test_fileread.py
> +sys.path.append(os.getcwd())
This should you never need to do.

2020-10-12 14:28 UTC, paulboone commented on tests/test_fileread.py
> +    assert set(out_fileread(os.getcwd()+ '/tests')) == set(['coumarin_gas.out'\
there is a correct way of getting package-local files for testing that we will look up

2020-10-15 14:04 UTC, paulboone requested changes
So new commits are clearly named and it easy to follow. Since this is all new code though, you can squash some of the changes:

* "adding .egg-info to .gitignore" can go in initial .gitignore commit
* "removing whitespace and debugging code" can be squashed in to where you added the file

If we had already merged your prior commits, then the new atomic commits would be perfect for making the fixes. Since we haven't merged, we have the opportunity to clean up the commits so it looks like you did it right the first time. :)

See other comments.

2020-10-15 14:04 UTC, paulboone commented on .gitignore
> +amesQSAR.egg-info/
*.egg-info would be more general

2020-10-15 14:04 UTC, paulboone commented on tests/test_fileread.py
> +    assert set(out_fileread(THIS_DIR)) == set(['coumarin_gas.out'\
so I just dealt with this for the integration tests I'm working on. You will want to:
* use the `tmpdir` fixture
* cd to the tmpdir at the beginning of the test (so the files get created there)
* check for their existence there.
I will go over all this on Monday, too.

2020-10-15 14:04 UTC, paulboone commented on tests/test_fileread.py
pep8 module ordering:

Imports should be grouped in the following order:

    Standard library imports.
    Related third party imports.
    Local application/library specific imports.

You should put a blank line between each group of imports.

2020-10-15 14:04 UTC, paulboone commented on ames_qsar/out_fileread.py
>  def out_fileread(filepath):
add blank line between imports and def

2020-10-18 13:55 UTC, twsleight commented on tests/test_fileread.py
> +    assert set(out_fileread(THIS_DIR)) == set(['coumarin_gas.out'\
In my case these files aren't actually created by the script, they're already in existence in the test folder. The test checks the functions ability to find them all.

2020-11-05 15:03 UTC, closed without merging