Get homo lumo energies
pitt-software-practices/ames_qsar pull request #6
Opened 2020-11-01 16:47 UTC by twsleight

Adding another function and a test to get the HOMO and LUMO energies out of a .out script.

also:

.travis.yml and setup.py files included to make sure that it worked on Travis.

requirements.txt simplified

2020-11-02 15:30 UTC, monshap commented on ames_qsar/gethlenergy.py
> +                errorFlag = 1
Raise error here, so you don't run through the rest of the code.

2020-11-02 15:32 UTC, paulboone requested changes
Changes to the new homolumo functions!

2020-11-02 15:32 UTC, paulboone commented on tests/test_gethlenergy.py
> +    assert(h == -0.29586 and l == -0.04159)
hl = gethlenergy(dir_path, filename)
assert hl == [-0.29586, -0.04159]

2020-11-02 15:32 UTC, paulboone commented on tests/test_gethlenergy.py
> +    assert(h == -0.29586 and l == -0.04159)
shouldn't need print

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +
) as

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +    os.chdir(dir_path)
don't chdir

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +    termFlag = 0
term_flag

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +                a1 = a1. split()
'. '

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +
b = float(right[:56].split()[0])

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +            left,sep,right=line.partition('Alpha virt. eigenvalues --')
whitespace 'left,sep,right'

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +            prevLine2 = prevLine
delete?

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +            left,sep,right=line.partition('Alpha virt. eigenvalues --')
if 'Alpha virt. eigenvalues --' in line and 'Alpha  occ. eigenvalues --' in prev_line:

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +            print(filename, ' did not terminate correctly')
raise an exception?

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +        #********************
consider removing the print?

2020-11-02 15:32 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +        #************************
#******* comment => generally don't do this

2020-11-02 15:32 UTC, paulboone commented on setup.py
> +
replace this with just putting packages directly into setup.py

2020-11-04 03:48 UTC, twsleight commented
updates made and force pushed

2020-11-05 03:32 UTC, bayerl approved these changes

2020-11-05 15:19 UTC, paulboone requested changes

2020-11-05 15:19 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +    with open((dir_path + '/' + filename)) as searchfile:
os.path.join(dir_path, filename)

2020-11-05 15:19 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +    with open((dir_path + '/' + filename)) as searchfile:
don't do this here, but you should know about this: "%s/%s" % (dir_path, filename)

2020-11-05 15:19 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +        if term_flag ==0:
term_flag => normal_termination or terminated_normally:
terminated_normally = True
if not terminated_normally:

2020-11-05 15:19 UTC, paulboone commented on ames_qsar/gethlenergy.py
> +                #b = float(b1[0])
delete, not comment

2020-11-05 15:19 UTC, paulboone commented on ames_qsar/gethlenergy.py
> -                #b = float(b1[0])
this could be squashed

2020-11-05 15:19 UTC, paulboone commented on setup.py
> -
squash with prior requirement changes

2020-11-05 19:20 UTC, twsleight commented
updates from Thursday rebased and force pushed

2020-11-12 02:21 UTC, twsleight commented
merged the getHOMOLUMOenergies branch with master so the commits updated. Resolved the merge conflicts locally and force pushed, which updated the PR. This seems to have eliminated the merge conflicts.

2020-11-12 15:13 UTC, merged